name: Submit Dependency Graph

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true

permissions:
  contents: write

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GRADLE_SCRIPTS_PATH: project/gradle-scripts
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        env:
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: 'checkstyle'
        with:
          build-root-directory: project
          additional-arguments: |
            -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
            -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
